[env]
board_build.mbed.ldscript = true
board_build.arduino.ldscript = $PROJECT_DIR/linker_script_reserved_sram3.ld
board_build.variant = ${PROJECT_DIR}/../platformio_variants/generated/GENERIC_STM32H747_M4
platform_packages =
  platformio/framework-arduino-mbed@4.2.1
build_flags =
  -DDEVICE_USBDEVICE=1
  -Wl,--wrap=_Z11get_usb_phyv
build_unflags =
  -Wno-missing-field-initializers

[env:gatekeeper_m4_usb_gateway]
platform = ststm32
board = giga_r1_m4
framework = arduino
debug_tool = stlink
upload_protocol = custom

extra_scripts = pre:../platformio_tools/platformio_generate_variants.py
  pre:../platformio_tools/gen_compile_commands.py
  pre:../platformio_tools/inject_firmware_version.py
  pre:../platformio_tools/platformio_usb_bundle_upload.py
  pre:../platformio_tools/platformio_upload_persistence.py

debug_build_flags =
  -O0
  -g3

debug_init_break = tbreak main

build_flags =
  ${env.build_flags}


[env:gatekeeper_m4_usb_gateway_stlink]
platform = ststm32
board = giga_r1_m4
framework = arduino
debug_tool = stlink
upload_protocol = stlink

extra_scripts = pre:../platformio_tools/platformio_generate_variants.py
  pre:../platformio_tools/gen_compile_commands.py
  pre:../platformio_tools/inject_firmware_version.py
  pre:../platformio_tools/platformio_upload_persistence.py

debug_build_flags =
  -O0
  -g3

debug_init_break = tbreak main

build_flags =
  ${env.build_flags}
