[platformio]
default_envs = gatekeeper_firmware
src_dir = platformio_tools/upload_dispatcher_src

[env:gatekeeper_firmware]
platform = native
upload_protocol = custom
extra_scripts = pre:platformio_tools/platformio_product_upload.py
