[platformio]
default_envs = new_hardware
src_dir = platformio_tools/upload_dispatcher_src

[env:new_hardware]
platform = native
upload_protocol = custom
extra_scripts = pre:platformio_tools/platformio_product_upload.py
custom_gatekeeper_hardware = new_hardware

[env:old_hardware]
platform = native
upload_protocol = custom
extra_scripts = pre:platformio_tools/platformio_product_upload.py
custom_gatekeeper_hardware = old_hardware

[env:new_shield_old_dac_adc]
platform = native
upload_protocol = custom
extra_scripts = pre:platformio_tools/platformio_product_upload.py
custom_gatekeeper_hardware = new_shield_old_dac_adc
