[env:giga_r1_m7]
platform = ststm32
board = giga_r1_m7
framework = arduino
debug_tool = stlink
upload_protocol = custom
board_build.variant = ${PROJECT_DIR}/../platformio_variants/GIGA

extra_scripts = pre:../platformio_tools/gen_compile_commands.py
  pre:../platformio_tools/inject_firmware_version.py
  pre:../platformio_tools/platformio_usb_bundle_upload.py
  pre:../platformio_tools/platformio_pre_upload.py
  pre:../platformio_tools/platformio_post_upload.py

debug_build_flags =
  -O0
  -g3

debug_init_break = tbreak main

build_flags =
  -D__NEW_DAC_ADC__
  -D__NEW_SHIELD__

[env:gatekeeper_new_hardware]
extends = env:giga_r1_m7

[env:gatekeeper_old_hardware]
extends = env:giga_r1_m7

build_flags =
  -D__OLD_DAC_ADC__
  -D__OLD_SHIELD__

[env:gatekeeper_new_shield_old_dac_adc]
extends = env:giga_r1_m7

build_flags =
  -D__OLD_DAC_ADC__
  -D__NEW_SHIELD__


[env:giga_r1_m7_stlink]
platform = ststm32
board = giga_r1_m7
framework = arduino
debug_tool = stlink
upload_protocol = stlink
board_build.variant = ${PROJECT_DIR}/../platformio_variants/GIGA

extra_scripts = pre:../platformio_tools/gen_compile_commands.py
  pre:../platformio_tools/inject_firmware_version.py
  pre:../platformio_tools/platformio_pre_upload.py
  pre:../platformio_tools/platformio_post_upload.py

debug_build_flags =
  -O0
  -g3

debug_init_break = tbreak main

build_flags =
  -D__NEW_DAC_ADC__
  -D__NEW_SHIELD__

