[gatekeeper_m7_base]
platform = ststm32
board = giga_r1_m7
framework = arduino
debug_tool = stlink
upload_protocol = custom
board_build.variant = ${PROJECT_DIR}/../platformio_variants/generated/GIGA
platform_packages =
  platformio/framework-arduino-mbed@4.2.1

extra_scripts = pre:../platformio_tools/platformio_generate_variants.py
  pre:../platformio_tools/gen_compile_commands.py
  pre:../platformio_tools/inject_firmware_version.py
  pre:../platformio_tools/platformio_usb_bundle_upload.py
  pre:../platformio_tools/platformio_upload_persistence.py

debug_build_flags =
  -O0
  -g3

debug_init_break = tbreak main

[env:gatekeeper_m7_worker]
extends = gatekeeper_m7_base

[env:gatekeeper_m7_worker_stlink]
platform = ststm32
board = giga_r1_m7
framework = arduino
debug_tool = stlink
upload_protocol = stlink
board_build.variant = ${PROJECT_DIR}/../platformio_variants/generated/GIGA
platform_packages =
  platformio/framework-arduino-mbed@4.2.1

extra_scripts = pre:../platformio_tools/platformio_generate_variants.py
  pre:../platformio_tools/gen_compile_commands.py
  pre:../platformio_tools/inject_firmware_version.py
  pre:../platformio_tools/platformio_upload_persistence.py

debug_build_flags =
  -O0
  -g3

debug_init_break = tbreak main
