[env:giga_r1_m7]
platform = ststm32
board = giga_r1_m7
framework = arduino
debug_tool = stlink
upload_protocol = custom

extra_scripts = pre:../tools/gen_compile_commands.py
  pre:../tools/inject_firmware_version.py
  pre:../tools/platformio_usb_bundle_upload.py
  pre:../tools/platformio_pre_upload.py
  pre:../tools/platformio_post_upload.py

debug_build_flags =
  -O0
  -g3

debug_init_break = tbreak main

build_flags =
  -DDAC_ADC_DISABLE_M7_USB_CDC
  -D__NEW_DAC_ADC__
  -D__NEW_SHIELD__


[env:giga_r1_m7_stlink]
platform = ststm32
board = giga_r1_m7
framework = arduino
debug_tool = stlink
upload_protocol = stlink

extra_scripts = pre:../tools/gen_compile_commands.py
  pre:../tools/inject_firmware_version.py
  pre:../tools/platformio_pre_upload.py
  pre:../tools/platformio_post_upload.py

debug_build_flags =
  -O0
  -g3

debug_init_break = tbreak main

build_flags =
  -DDAC_ADC_DISABLE_M7_USB_CDC
  -D__NEW_DAC_ADC__
  -D__NEW_SHIELD__


[env:giga_r1_m7_usb_upload_guard]
platform = ststm32
board = giga_r1_m7
framework = arduino
debug_tool = stlink
upload_protocol = stlink

extra_scripts = pre:../tools/gen_compile_commands.py
  pre:../tools/inject_firmware_version.py

debug_build_flags =
  -O0
  -g3

debug_init_break = tbreak main

build_flags =
  -DDAC_ADC_DISABLE_M7_USB_CDC
  -D__NEW_DAC_ADC__
  -D__NEW_SHIELD__
  -DDAC_ADC_USB_UPLOAD_GUARD

build_src_filter =
  +<main.cpp>
