#pragma once

constexpr int NUM_CHANNELS_PER_DAC_BOARD = 4;
constexpr int NUM_CHANNELS_PER_ADC_BOARD = 4;
constexpr int NUM_DAC_BOARDS = 2;
constexpr int NUM_ADC_BOARDS = 2;
constexpr int NUM_DAC_CHANNELS = NUM_DAC_BOARDS * NUM_CHANNELS_PER_DAC_BOARD;
constexpr int NUM_ADC_CHANNELS = NUM_ADC_BOARDS * NUM_CHANNELS_PER_ADC_BOARD;
constexpr int NUM_DAC_CALIBRATION_CHANNELS = NUM_DAC_CHANNELS;
constexpr int NUM_ADC_CALIBRATION_CHANNELS = NUM_ADC_CHANNELS;
